### ISSUE TITLE
Decimal Approximation has issues when floating numbers are used.

### ISSUE THREAD

**Issue by udnisap** [infusion/Fraction.js#10]
When flotting numbers are used fractions are round. 
```
Fraction('999999.99') ===Fraction(999999.99) // returns false
999999.99 == 999999.99 // returns true
Fraction('999999.99').valueOf() // 999999.99
Fraction(999999.99).valueOf() // 1000000
````
Source code suggest http://www.johndcook.com/blog/2010/10/20/best-rational-approximation/
Is there any workaround to this or do we know when this approximation is fired in?

**Comment by infusion** [comment]
Hi,
you suggested the fix yourself. As I mentioned in the docs, the string parser works much more stable when it comes to parsing fixed decimal numbers. So, if you want to convert numbers like this to fractions, I suggest to cast them to string. For all other cases the link you posted is the best source I could find to a rational approximation and incorporated it therefore. When I finish my thesis, I'll work on a flexible backend for fraction.js and complex.js so that numerator and denominator can be based on bignumber.js for example. This will help folks over at math.js as well, since imprecision due to double arithmetic is the root cause for many bug tickets.

If you worry about performance, the string parser is obviously O(log n) and shouldn't be the bottleneck. The error here is (1-999999.99/1000000)*100 = 1e^-6%. If you need that precision in your application, the cast shouldn't be a problem - especially since you can cache the fraction objects after initialization. 

Sorry for having no better news for you for now.

Robert
