### ISSUE TITLE
0.333 is returned as 333/1000

### ISSUE THREAD

**Issue by jdcauley** [infusion/Fraction.js#17]
This Library is great but I'm not sure if this is a bug or something else.

I'm expecting to get 1/3 from 0.333 but instead get 333/1000.

Am I missing something?

**Comment by infusion** [comment]
Thanks! 
The library tries to be as precise as the underlaying data type allows and the best rational approximation of 0.333 is 333/1000 and not 1/3. I was thinking quite a lot about this. When you run `new Fraction(1/3)` you'll get 1/3 out, which is not be the case for `new Fraction('0.3333333333')`, since the string is finite. 

That brought me to the point that strings are always finite and doubles are made rational using farey sequences, which is arguably one of the best rational approximations. 

I was thinking about a method to simplify rational numbers according to a parametrized allowed error, for which a fraction like 333/1000 could be 1/3 with a reasonable epsilon. However, I did not implement that function yet. For the use case you're addressing here, I wrote a small utility function `formatDecimal` for the readme back then. It's not pretty robust and really just the result of a few minutes but maybe you can build on that.

Robert

**Comment by infusion** [comment]
An alternative would be to wrap brackets around the 3's: `new Fraction('0.(333)')` instead of `new Fraction('0.333')`

Robert

**Comment by infusion** [comment]
Okay, I implemented a routine called `simplify` to make exactly that work. The code is not performance optimized yet, but this will be improved before the next release. Could you give it a trial?

```
new Fraction("0.333").simplify(0.001) // becomes 1/3
```

Robert

**Comment by ndstephens** [comment]
Same issue.  Tried your simplify method.  Solved my issue.  Thanks!!
