### ISSUE TITLE
Trailing 0's when casting a fraction to string

### ISSUE THREAD

**Issue by QuteBits** [infusion/Fraction.js#19]
Sometimes using `toString()` method returns a stringified number with trailing zeroes.

Example - enter that in your browser console:
`var a = new Fraction(1); var b = new Fraction(0.99); var c = new Fraction(0.98); for (var i = 0; i < 100; i++) { a = a.mul(b).div(c); console.log(a.toString()); }`

and you will see that numbers like: `1.455919622856570`, `1.470775945538780`, `1.485783863350400`

**Comment by infusion** [comment]
Thanks for this issue. I reflected quite some time on this and on first sight, this really seems like an issue. Even if you take this example, which I added to the test suite: 

```
new Fraction(".0000000000000003").toString() // == "0.000000000000000"
```

But let me explain the rationale behind the whole: `1/2` is `"0.5"` and not `"0.500000000000000"`, as expected. This is because the significant figures are just `.5`. Another thing is given for the code you've given, where one of the first fractions is `6869570742453802/5329686054127205` - or `"1.288925965373540"`. When you ask wolframalpha, you get more digits, like: `1.288925965373540212763657620354723980596170653178263942835...`. And at some point I decided to hard-code the number of decimal places to be *15*. I reverted that decision and made the precision an optional parameter like `toString([places=15])`, since there is no reason that 15 should be the only possible number. 
Anyway, you see the trailing zeros, since they are important as significant figures for the requested precision. If you really don't like them for esthetic reasons, you can remove them with a simple regex yourself, like

```
str = "1.23000".replace(/(\.\d*[1-9]|\.0)0+$/, '$1'); // 1.23
```

I tend to leave the library as precise as possible - but this does not match any use case of course. But for this problem, I think its the best solution to retouch the result yourself, if really wanted.

Best Robert

**Comment by QuteBits** [comment]
True. I guess I was a bit too fast with opening the issue (arrived to the same conclusion as you yesterday evening). Thank you for a very fast and explanatory answer.
