### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hundry1986** [infusion/Fraction.js#20]
Fraction.js/LICENSE   ->  MIT License
Fraction.js/fraction.min.js  ->  Dual licensed under the MIT or GPL Version 2 licenses.
Fraction.js/fraction.js  ->  Dual licensed under the MIT or GPL Version 2 licenses.

Which is Fraction.js license? MIT ? MIT & GPLv2?

**Comment by hundry1986** [comment]
I don't know either. 
Maybe you can move the copyright to the top of README.md (I see it at the bottom of README.md). I didn't notice that before added it to git and saw the source code. 
And just curious, why do you select dual license? 
If I add it to my project, which license should I obey? MIT & GPLv2 license contradict each other sometimes.

**Comment by infusion** [comment]
Under a dual license you can choose the license which better fits your needs. Personally, I'm more the MIT guy, like share everything as long as the original source is mentioned, but if you want to use it in a more restrictive environment, you can go with GPL. That's also why I chose two licenses, because people contact me sometimes to re-license things as they have a more restrictive/open policy.
Nahh, I want to keep the license at the bottom as it is the most irrelevant thing when you come to an unknown repository and want to know something about it. The info is there and most usually, the LICENSE file with MIT can be used.

**Comment by hundry1986** [comment]
That's Great! Thanks for your reply!
