### ISSUE TITLE
new Fraction(value) fails when not using en-US decimal format

### ISSUE THREAD

**Issue by jlucaspains** [infusion/Fraction.js#57]
So I'm building an app that uses fraction.js to parse text user input and perform conversions from/to fraction as well as multiplications. The app accepts input in multiple languages and is running into trouble because of locale.

A simplified use case:
```typescript
const quantity = "1,5"; // note that this is valid decimal in Brazil (pt-BR)
const fraction = new Fraction(quantity);
```

The above use case fails with `Error: Invalid argument`. If the user enters 1.5 for quantity, it will work. 

As a solution, the consumer of `Fraction` could simply pass an optional locale argument. When not provided, the library can either assume a locale or do what it is doing today.

There might be other edge cases, but this is the one I'm running into right now. Is this something beneficial for this library? If it is, I am willing to try and implement this and submit a PR.

**Comment by jlucaspains** [comment]
One argument against implementing this is that even `parseFloat()` doesn't offer locale-based parsing...

**Comment by infusion** [comment]
I like this idea, but since Fraction.js should be fairly small when packaged and only a small portion of input strings would be covered, namely numbers with fractional part, this is either a good idea of an own library that translates the locales, or by fixing it before passing it to Fraction.js. 

Here in Germany, we probably have the format as you, "123,45" and "123.456,99" with 1000s separators. Fixing this is usually just removing the dots and replacing the `,` by `.`. When you need it more flexible based on the locale, you could use something around the new `Intl` object, as outlined here https://observablehq.com/@mbostock/localized-number-parsing

But as I said, this only covers numbers like `"123,45"`, fractions can also be `"123/456"` or `"44 123/456"`. So maybe checking if no `[ /:]` exists in the string could lead to the `NumberParser` approach stated on the referenced site.

**Comment by jlucaspains** [comment]
No worries. After I put the issue I spent some time researching how this is done and realized it is probably best done elsewhere. For folks reading this in the future, this is how I've done it:

```typescript
function localeParseFloat(s: string, locale: string) {
    // Get the thousands and decimal separator characters used in the locale.
    let [, thousandsSeparator, , , , decimalSeparator] = 1111.1.toLocaleString(locale);

    const cleanInput = s.replace(thousandsSeparator, "").replace(decimalSeparator, ".");

    // Now it can be parsed
    return parseFloat(cleanInput);
}
```
I got the original from [StackOverflow](https://stackoverflow.com/a/59679285) and adapted a bit to make it smaller.
