### ISSUE TITLE
Support for "d:n" besides "d/n"

### ISSUE THREAD

**Issue by Martien** [infusion/Fraction.js#61]
Feature request: `.toFraction()` returns `"n/d"`. Sometimes, you need/prefer `"n:d"`, e.g. when working in music theory or with aspect ratios.

My work around now is to add a separate function to the object returned by Fraction using `Object.assign()` in a wrapper.

Also, would the separator be an extra argument to `.toFraction()` or would it rather be a new function, e.g. `.toRatio()`?

**Comment by infusion** [comment]
Ahh, you're coming from a music-theoretic background. This also explains #62. :) I think the easiest way here is also just replacing the slash by a colon outside Fraction.js like 

```js
Fraction(1, 2).toFraction().replace("/", ":")
```

which is save, as the function only returns strings. A function `.toRatio()` is probably a bit misleading, since it is exactly the same as `toFraction()` with a colon in between. But since `toLatex()` and `toFraction()` are already pretty much the same, there could also be a more abstract way, such as with a format string:

```js
toFormat("%n/%d") // 3/4
toFormat("%n:%d") // 3:4
toFormat("\\frac{%n}{%d}") // \frac{3}{4}
```
and maybe something like %w to express the exclusion of wholes, such as

```js
toFormat("%w %n/%d") // 5 1/2
```
Internally this would require quite a few string replacements, which would slow down the function. On top of that, the syntax isn't clear anymore.

**Comment by Martien** [comment]
Thanks for the reply. I’ll go with the `.replace("/", ":")`. Works fine for now.
