### ISSUE TITLE
Common denominator for list of fractions

### ISSUE THREAD

**Issue by Martien** [infusion/Fraction.js#62]
Feature request: support for creating common denominator for list of fractions.

I need `Fraction(4, 4)` to return `{s: 1, n: 4, d: 4}` instead of simplifying it to `{s: 1, n: 1, d: 1}`.

Also, I need a function that takes a list like:
```
[
  Fraction(2, 1), 
  Fraction(3, 2),
  Fraction(4, 3),
  Fraction(5, 4),
  Fraction(6, 5),
]
```
and returns:
```
[
  {s: 1, n: 120, d: 60},
  {s: 1, n:  90, d: 60},
  {s: 1, n:  80, d: 60},
  {s: 1, n:  75, d: 60},
  {s: 1, n:  72, d: 60},
]
```
That is, the fractions have a common denominator equal to `lcm(1,2,3,4,5,6) → 60`. The converted list of fractions is easier to compare (just sort on the nominator).

**Comment by infusion** [comment]
I think this lacks one important thing: Fraction.js always reduces fractions immediately. So scaling by 60/60 scales by 1. But your use-case should be possible with Fraction.js pretty straightforward:

```javascript
const arr = [
  Fraction(2, 1), 
  Fraction(3, 2),
  Fraction(4, 3),
  Fraction(5, 4),
  Fraction(6, 5),
];

const lcm = arr.reduce((a, b) => a.lcm(b), new Fraction(1));

const result = arr.map(x => ({s: 1, n: x.n * lcm.n / x.d, d: lcm.n}));
```

Which results in exactly your desired output:

```
[
  {s: 1, n: 120, d: 60},
  {s: 1, n:  90, d: 60},
  {s: 1, n:  80, d: 60},
  {s: 1, n:  75, d: 60},
  {s: 1, n:  72, d: 60},
]
```

**Comment by Martien** [comment]
Thanks for your quick, elaborate and helpful reply. Works as advertised.

Yet, the result is a list of Objects rather than Fractions. I’d like to standardize on a single type throughout, preferably Fraction. Perhaps Tone as new type, as an augmented class of Fraction.

What is the rationale for Fraction.js to immediately reduce the fraction? What are the objections against not reducing?

Also, should future versions of Fraction.js add support for these kind of things?

**Comment by infusion** [comment]
The strongest reason for the immediate reduction is numerical stability. Most problems that arise - also that come up as issue here - are due to overflows, which can occur even with a few simple additions, since you must scale for a common denominator each time. There was an option already present in the past, called `Fraction.REDUCE = false`, which allowed to turn off the reduction. Ultimately, this feature was removed after causing other internal problems since you have to think through this for every function.  

So as Fraction.js deals with ratios the decision was made to always keep the reduced form. I don't know what you're trying to achieve, but what you could do is copying over the internal function `newFraction()` and use it in a modified form outside the Fraction.js scope like so:

```javascript
function newFraction(n, d) {

  if (d === 0) {
    throw Fraction['DivisionByZero'];
  }

  var f = Object.create(Fraction.prototype);
  f["s"] = n < 0 ? -1 : 1;

  n = n < 0 ? -n : n;

  f["n"] = n;
  f["d"] = d;
  return f;
}

const lcm = arr.reduce((a, b) => a.lcm(b), new Fraction(1));

const result = arr.map(x => newFraction(x.n * lcm.n / x.d, d: lcm.n));
```

This keeps the objects in a Fraction.js envelope, but of course does not prevent Fraction.js to reduce the ratio after upcoming operations.

**Comment by Martien** [comment]
I see. Thanks for pointing that out.

Also thanks for the modification suggestion. I’ll absorb it into my experiment.

Have a nice week.
